name: Setup

inputs:
  toolchain:
    description: “Rust toolchain name”
    default: stable
    required: false
  components:
    description: “Rust toolchain components to install”
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{inputs.toolchain}}
        override: true
        components: ${{inputs.components}}
